### ISSUE TITLE
ERROR : Failed to bind image memory

### ISSUE THREAD

**Issue by Limiao813** [maelaubert/VulkanSift#1] opened 2021-07-15 08:05 UTC
hello

I meet this error in my project, the image is 5472 * 3648.

[vkenv:VulkanUtils] #Unexpected VkResult value: -1000011001#
[vkenv:VulkanUtils] Failed to bind image memory (vkBindImageMemory: #Unexpected VkResult value#)
[vkenv:SiftMemory] An error occured when setting up the octave images
[vkenv:SiftMemory] Failed to update the Vulkan images for the new input resolution
[vkenv:VulkanSift] vksift_detectFeatures() error: Failed to prepare the SiftMemory instance for the input image and target buffer

**Comment by maelaubert** [comment] 2021-07-15 10:16
Hi @Limiao813 

I looked into this error and was able to reproduce it with a slightly smaller image. You probably had the same Vulkan validation layer (only enabled in Debug) error message:

``
VUID-vkBindImageMemory-size-01049(ERROR / SPEC): msgNum: 0 - vkBindImageMemory(): memory size minus memoryOffset is 0x12bec000 but must be at least as large as VkMemoryRequirements::size value 0x12c96000, returned from a call to vkGetImageMemoryRequirements with image. The Vulkan spec states: The size member of the VkMemoryRequirements structure returned from a call to vkGetImageMemoryRequirements with image must be less than or equal to the size of memory minus memoryOffset (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkBindImageMemory-size-01049)
    Objects: 1
        [0] 0x13e000000013e, type: 10, name: NULL
``

It seems that it's due to some typo in the memory management code. I committed a fix in the 'fix_bind_image_memory' branch, let me now if that works for you!

**Closed as completed** 2021-08-22 14:50 UTC
